import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  OneToMany,
} from 'typeorm';
import { Page } from '../pages/page.entity';

export enum SiteStatus {
  IDLE = 'idle',
  PARSING = 'parsing',
  DONE = 'done',
  ERROR = 'error',
}

export enum EmbeddingStatus {
  IDLE = 'idle',
  EMBEDDING = 'embedding',
  DONE = 'done',
  ERROR = 'error',
}

@Entity('sites')
export class Site {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ length: 255 })
  name: string;

  @Column({ length: 255 })
  url: string;

  @Column({ length: 500 })
  sitemapUrl: string;

  @Column({ length: 500, nullable: true })
  favicon: string | null;

  /** API key generated by the WP plugin — used in X-Poirier-API-Key header */
  @Column({ length: 100, nullable: true })
  wpApiKey: string | null;

  /** Google Search Console property URL, e.g. https://example.com/ or sc-domain:example.com */
  @Column({ length: 500, nullable: true })
  gscProperty: string | null;

  /** Whether this site is hosted on WP Engine — gates the WP Engine cache-purge layer. */
  @Column({ type: 'boolean', default: false })
  hostedOnWpEngine: boolean;

  @Column({ type: 'enum', enum: SiteStatus, default: SiteStatus.IDLE })
  status: SiteStatus;

  @Column({ default: 0 })
  pagesTotal: number;

  @Column({ default: 0 })
  pagesProcessed: number;

  @Column({ type: 'timestamp', nullable: true })
  lastParsedAt: Date | null;

  @Column({ type: 'enum', enum: EmbeddingStatus, default: EmbeddingStatus.IDLE })
  embeddingStatus: EmbeddingStatus;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @OneToMany(() => Page, (page) => page.site, { cascade: true })
  pages: Page[];
}
