import { useState, useEffect } from 'react'
import { Link, useParams, Navigate, useSearchParams } from 'react-router-dom'
import { formatDistanceToNow, format } from 'date-fns'
import { toast } from 'sonner'
import {
  ChevronRight, ExternalLink, RefreshCw,
  ChevronLeft,
  FileText, Upload, CheckCircle2, XCircle, Settings, Sparkles,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import {
  Sheet, SheetContent, SheetHeader, SheetTitle, SheetFooter,
} from '@/components/ui/sheet'
import { StatusBadge, EmbeddingBadge } from '@/components/StatusBadge'
import { WpPluginStatus } from '@/components/WpPluginStatus'
import { GscStatus } from '@/components/GscStatus'
import { PsiStatus } from '@/components/PsiStatus'
import { useSite, useParseSite, useUpdateSite } from '@/hooks/useSites'
import { useGscSiteStatus } from '@/hooks/useGsc'
import { usePages } from '@/hooks/usePages'
import { useSyncStatus, useTriggerSync } from '@/hooks/useSync'
import { useEmbeddingStats, useGenerateEmbeddings } from '@/hooks/useEmbedding'
import { Label } from '@/components/ui/label'
import { McpChangesPanel } from '@/components/McpChangesPanel'
import { IndexStatusOverviewCard } from '@/components/index-status/IndexStatusOverviewCard'
import type { Site } from '@/api/sites'
import type { McpChangeModule } from '@/api/mcpChanges'

const PAGE_LIMIT = 50

function relativeTime(date: string | null) {
  if (!date) return 'Never'
  return formatDistanceToNow(new Date(date), { addSuffix: true })
}

/* ──────────────────────────────── Site Settings Sheet ──────────────────────── */

function SiteSettingsSheet({ site, onClose }: { site: Site | null; onClose: () => void }) {
  const [apiKey, setApiKey] = useState('')
  const update = useUpdateSite()
  const { data: gscSiteStatus, isLoading: gscLoading } = useGscSiteStatus(site?.url)

  useEffect(() => {
    if (site) setApiKey(site.wpApiKey ?? '')
  }, [site?.id]) // eslint-disable-line react-hooks/exhaustive-deps

  async function handleSave() {
    if (!site) return
    try {
      await update.mutateAsync({
        id: site.id,
        payload: { wpApiKey: apiKey.trim() || null } as any,
      })
      toast.success('Settings saved')
      onClose()
    } catch {
      toast.error('Failed to save settings')
    }
  }

  return (
    <Sheet open={!!site} onOpenChange={(o) => !o && onClose()}>
      <SheetContent side="right" className="w-[420px] sm:max-w-[420px] bg-[#1a1d27] border-l border-white/8 flex flex-col p-0">
        <SheetHeader className="px-6 py-4 border-b border-white/8 flex-shrink-0">
          <SheetTitle className="text-[#e8eaed] text-[15px] font-semibold">Site Settings</SheetTitle>
          {site && (
            <p className="text-[12px] text-[#9aa0a6] mt-0.5 truncate">{site.name}</p>
          )}
        </SheetHeader>

        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-6">
          <div className="space-y-2">
            <Label className="text-[#9aa0a6] text-[11px] font-medium uppercase tracking-widest">
              WordPress API Key
            </Label>
            <input
              type="text"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              placeholder="Paste key from WP admin → Settings → Poirier CMS"
              className="w-full bg-[#0f1117] border border-white/8 rounded-lg px-3 py-2.5 text-sm text-[#e8eaed] placeholder:text-[#9aa0a6]/40 font-mono focus:outline-none focus:ring-1 focus:ring-[#4e8af4]/50 focus:border-[#4e8af4]/40 transition-colors"
            />
            <p className="text-[11px] text-[#9aa0a6]/60 leading-relaxed">
              Generated by the Poirier CMS plugin installed on the WordPress site.
              Required for pushing meta changes.
            </p>
          </div>

          {/* GSC Status */}
          <div className="space-y-2">
            <Label className="text-[#9aa0a6] text-[11px] font-medium uppercase tracking-widest">
              Google Search Console
            </Label>
            {gscLoading ? (
              <div className="flex items-center gap-2 px-3 py-2.5 rounded-lg bg-[#0f1117] border border-white/8 text-[13px] text-[#9aa0a6]">
                <RefreshCw className="size-3.5 animate-spin" />
                Checking connection…
              </div>
            ) : gscSiteStatus?.connected ? (
              <div className="flex items-center gap-2 px-3 py-2.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-[13px]">
                <CheckCircle2 className="size-4 text-emerald-400 flex-shrink-0" />
                <div className="min-w-0">
                  <p className="text-emerald-400 font-medium">Connected</p>
                  <p className="text-[11px] text-emerald-400/70 font-mono truncate mt-0.5">
                    {gscSiteStatus.property}
                  </p>
                </div>
              </div>
            ) : (
              <div className="flex items-start gap-2 px-3 py-2.5 rounded-lg bg-[#0f1117] border border-white/8 text-[13px]">
                <XCircle className="size-4 text-[#9aa0a6] flex-shrink-0 mt-0.5" />
                <div>
                  <p className="text-[#9aa0a6]">
                    {gscSiteStatus?.reason === 'no_credentials'
                      ? 'No credentials file - see Settings'
                      : 'Domain not found in Search Console'}
                  </p>
                  {gscSiteStatus?.reason === 'domain_not_found' && (
                    <p className="text-[11px] text-[#9aa0a6]/60 mt-0.5">
                      Add the service account as Full User in GSC
                    </p>
                  )}
                </div>
              </div>
            )}
          </div>

          <div className="rounded-lg border border-white/8 bg-[#0f1117] p-4 space-y-3">
            <p className="text-[11px] font-semibold text-[#9aa0a6] uppercase tracking-widest">Plugin setup</p>
            <ol className="space-y-2 text-[12px] text-[#9aa0a6] list-decimal list-inside leading-relaxed">
              <li>Download <code className="text-[#4e8af4] text-[11px]">poirier-cms.zip</code> from the CMS repo</li>
              <li>In WP admin go to <strong className="text-[#e8eaed]">Plugins → Add New → Upload</strong></li>
              <li>Activate <strong className="text-[#e8eaed]">Poirier CMS Connector</strong></li>
              <li>Go to <strong className="text-[#e8eaed]">Settings → Poirier CMS</strong> and copy the API key</li>
              <li>Paste it above and save</li>
            </ol>
            {site && (
              <div className="pt-1 border-t border-white/8">
                <p className="text-[11px] text-[#9aa0a6]/60 mb-1">WP endpoint that will be called:</p>
                <code className="text-[10px] text-[#4e8af4] break-all">
                  {site.url}/wp-json/poirier-cms/v1/update-meta
                </code>
              </div>
            )}
          </div>
        </div>

        <SheetFooter className="px-6 py-5 border-t border-white/8 flex-shrink-0 flex gap-3">
          <Button variant="ghost" onClick={onClose} className="flex-1 h-10 text-[#9aa0a6] hover:text-[#e8eaed] hover:bg-white/5">
            Cancel
          </Button>
          <Button
            onClick={handleSave}
            disabled={update.isPending}
            className="flex-1 h-10 bg-[#4e8af4] hover:bg-[#4e8af4]/90 text-white"
          >
            {update.isPending ? <><RefreshCw className="size-4 mr-2 animate-spin" />Saving…</> : 'Save'}
          </Button>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  )
}

/* ──────────────────────────────── Stat Card ────────────────────────────────── */

function StatCard({ label, value, subtitle }: { label: string; value: string | number; subtitle?: string }) {
  return (
    <div className="rounded-xl border border-white/8 bg-[#1a1d27] px-5 py-4">
      <p className="text-[11px] font-medium uppercase tracking-widest text-[#9aa0a6] mb-1">{label}</p>
      <p className="text-2xl font-semibold text-[#e8eaed] tabular-nums">{value}</p>
      {subtitle && <p className="text-[11px] text-[#9aa0a6]/60 mt-1.5">{subtitle}</p>}
    </div>
  )
}

function nextScheduledScan(): string {
  const now = new Date()
  const next = new Date(now)
  next.setHours(2, 0, 0, 0)
  if (next <= now) next.setDate(next.getDate() + 1)
  return `Next scan ${formatDistanceToNow(next, { addSuffix: true })} · ${format(next, 'MMM d, 02:00')}`
}

/* ──────────────────────────────── Main Page ────────────────────────────────── */

export default function SiteDetailPage() {
  const { id } = useParams<{ id: string }>()
  const [searchParams] = useSearchParams()
  const focusModule = (searchParams.get('module') as McpChangeModule | null) ?? null
  const [settingsOpen, setSettingsOpen] = useState(false)

  const { data: site, isLoading: siteLoading } = useSite(id!)
  const isParsing = site?.status === 'parsing'
  const isEmbedding = site?.embeddingStatus === 'embedding'
  const { data: embeddingStats } = useEmbeddingStats(id!)
  const generateEmbeddings = useGenerateEmbeddings(id!)

  const { data: syncStatus } = useSyncStatus(id!)
  const triggerSync = useTriggerSync(id!)
  const pendingCount = (syncStatus?.pending ?? 0) + (syncStatus?.failed ?? 0)
  const isSyncing = (syncStatus?.syncing ?? 0) > 0

  const { data: pagesData, isLoading: pagesLoading } = usePages(
    id!, 1, PAGE_LIMIT, '', isParsing || isSyncing, 'url_asc',
  )
  const parseSite = useParseSite()

  async function handleApplyChanges() {
    try {
      await triggerSync.mutateAsync()
      toast.success('Pushing changes to WordPress…')
    } catch {
      toast.error('Failed to start sync')
    }
  }

  if (!id) return <Navigate to="/sites" replace />

  const meta = pagesData?.meta
  const customMetaCount = (pagesData?.data ?? []).filter(
    (p) => p.customMetaTitle || p.customMetaDescription,
  ).length

  async function handleReparse() {
    try {
      await parseSite.mutateAsync(id!)
      toast.success('Re-parsing started')
    } catch {
      toast.error('Failed to start parsing')
    }
  }

  async function handleGenerateEmbeddings() {
    try {
      await generateEmbeddings.mutateAsync()
      toast.success('Embedding generation started - this runs in the background')
    } catch {
      toast.error('Failed to start embedding generation')
    }
  }

  return (
    <div className="min-h-full">
      {/* Header */}
      <div className="border-b border-white/8 px-8 py-5">
        <div className="flex items-center gap-1.5 text-[13px] mb-3">
          <Link to="/sites" className="text-[#9aa0a6] hover:text-[#e8eaed] transition-colors flex items-center gap-1">
            <ChevronLeft className="size-3.5" />
            Sites
          </Link>
          <ChevronRight className="size-3.5 text-[#9aa0a6]/40" />
          <span className="text-[#e8eaed]">
            {siteLoading
              ? <Skeleton className="h-4 w-24 bg-white/5 inline-block" />
              : site?.name}
          </span>
        </div>

        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-3 min-w-0">
            {siteLoading ? (
              <Skeleton className="h-7 w-48 bg-white/5" />
            ) : (
              <>
                {site?.favicon && (
                  <img
                    src={site.favicon}
                    className="size-5 rounded-sm object-contain flex-shrink-0"
                    alt=""
                    onError={(e) => { (e.currentTarget as HTMLImageElement).style.display = 'none' }}
                  />
                )}
                <h1 className="text-xl font-semibold text-[#e8eaed] tracking-tight truncate">
                  {site?.name}
                </h1>
                <StatusBadge status={site?.status ?? 'idle'} />
                <EmbeddingBadge
                  status={site?.embeddingStatus ?? 'idle'}
                  embedded={embeddingStats?.embedded}
                  total={embeddingStats?.total}
                />
                <WpPluginStatus siteId={id!} />
                <GscStatus siteUrl={site?.url} />
                <PsiStatus siteId={id!} />
              </>
            )}
          </div>

          <div className="flex items-center gap-3 flex-shrink-0">
            {site && (
              <a
                href={site.url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-1.5 text-[13px] text-[#9aa0a6] hover:text-[#4e8af4] transition-colors"
              >
                <span className="max-w-[240px] truncate">{site.url}</span>
                <ExternalLink className="size-3.5 flex-shrink-0" />
              </a>
            )}
            {(pendingCount > 0 || isSyncing) && (
              <Button
                size="sm"
                onClick={handleApplyChanges}
                disabled={isSyncing || triggerSync.isPending}
                className="h-8 px-3 text-[13px] bg-[#4e8af4] hover:bg-[#4e8af4]/90 text-white gap-1.5 disabled:opacity-70 shadow-[0_0_12px_rgba(78,138,244,0.35)]"
              >
                {isSyncing ? (
                  <><RefreshCw className="size-3.5 animate-spin" />Syncing…</>
                ) : (
                  <>
                    <Upload className="size-3.5" />
                    Apply Changes
                    <span className="bg-white/20 text-white text-[10px] font-semibold px-1.5 py-0.5 rounded-full tabular-nums">
                      {pendingCount}
                    </span>
                  </>
                )}
              </Button>
            )}
            <Button
              size="sm"
              variant="ghost"
              onClick={() => setSettingsOpen(true)}
              className="h-8 w-8 p-0 text-[#9aa0a6] hover:text-[#e8eaed] hover:bg-white/5 border border-white/8"
              title="Site settings"
            >
              <Settings className="size-4" />
            </Button>
            <Button
              size="sm"
              onClick={handleGenerateEmbeddings}
              disabled={generateEmbeddings.isPending || isEmbedding}
              title={embeddingStats ? `${embeddingStats.embedded}/${embeddingStats.total} pages embedded` : 'Generate embeddings for AI search'}
              className="h-8 px-3 text-[13px] bg-[#232635] hover:bg-[#2a2f44] text-[#e8eaed] border border-white/8 gap-1.5 disabled:opacity-50"
            >
              {isEmbedding
                ? <RefreshCw className="size-3.5 animate-spin" />
                : <Sparkles className="size-3.5" />}
              Embeddings
              {embeddingStats && (
                <span className="text-[10px] text-[#9aa0a6] tabular-nums">
                  {embeddingStats.embedded}/{embeddingStats.total}
                </span>
              )}
            </Button>
            <Button
              size="sm"
              onClick={handleReparse}
              disabled={isParsing || isEmbedding || parseSite.isPending}
              className="h-8 px-3 text-[13px] bg-[#232635] hover:bg-[#2a2f44] text-[#e8eaed] border border-white/8 gap-1.5 disabled:opacity-50"
            >
              <RefreshCw className={`size-3.5 ${isParsing ? 'animate-spin' : ''}`} />
              Re-parse
            </Button>
          </div>
        </div>
      </div>

      <div className="px-8 py-6 space-y-6">
        {/* Stats */}
        <div className="grid grid-cols-3 gap-4 max-w-xl">
          <StatCard label="Total Pages" value={pagesLoading ? '-' : (meta?.total ?? 0).toLocaleString()} />
          <StatCard label="Modified" value={pagesLoading ? '-' : customMetaCount.toLocaleString()} />
          <StatCard
            label="Last Parsed"
            value={siteLoading ? '-' : relativeTime(site?.lastParsedAt ?? null)}
            subtitle={nextScheduledScan()}
          />
        </div>

        {/* Pending AI changes (human approval gate for MCP-originated edits) */}
        <McpChangesPanel siteId={id} focusModule={focusModule} />

        {/* Index status — coverage + what the last scan changed */}
        <IndexStatusOverviewCard siteId={id} parsing={isParsing} />

        {/* Pages entry point */}
        <Link
          to={`/sites/${id}/pages`}
          className="flex items-center justify-between gap-4 rounded-xl border border-white/8 bg-[#1a1d27] px-5 py-4 hover:bg-[#1f222e] hover:border-white/12 transition-colors group"
        >
          <div className="flex items-center gap-3 min-w-0">
            <div className="size-10 rounded-lg bg-[#4e8af4]/15 flex items-center justify-center flex-shrink-0">
              <FileText className="size-5 text-[#4e8af4]" />
            </div>
            <div className="min-w-0">
              <p className="text-[14px] font-medium text-[#e8eaed]">Pages</p>
              <p className="text-[12px] text-[#9aa0a6] mt-0.5">
                {pagesLoading
                  ? 'Loading…'
                  : `${(meta?.total ?? 0).toLocaleString()} pages · browse and inspect each page's structure`}
              </p>
            </div>
          </div>
          <ChevronRight className="size-5 text-[#9aa0a6] group-hover:text-[#e8eaed] transition-colors flex-shrink-0" />
        </Link>
      </div>

      <SiteSettingsSheet site={settingsOpen ? (site ?? null) : null} onClose={() => setSettingsOpen(false)} />
    </div>
  )
}
